all:lab3prob1 lab3prob2 lab3prob3
lab3prob1:cscd340lab3prob1.c
	gcc -g cscd340lab3prob1.c -o lab3prob1
lab3prob2:cscd340lab3prob2.c
	gcc -g cscd340lab3prob2.c -o lab3prob2
lab3prob3:cscd340lab3prob3.c
	gcc -g cscd340lab3prob3.c -o lab3prob3
clean:
	rm lab3prob1 lab3prob2 lab3prob3
