lab10:	cscd240_s13_lab10Tester.c
	gcc -o lab10 cscd240_s13_lab10Tester.c ./libinfileutil.a

lab10_2:	cscd240_s13_lab10Tester.c
	gcc -o lab10_2 cscd240_s13_lab10Tester.c ./libinfileutil.a ./dynamic/libfileutil.so.1
