all:prob1 prob2 prob3 prob4 prob5 prob6
prob1:lab5prob1.c
	gcc -g lab5prob1.c -o prob1 -lpthread
prob2:lab5prob2.c
	gcc -g lab5prob2.c -o prob2 -lpthread
prob3:lab5pc1.c
	gcc -g lab5pc1.c -o prob3 -lpthread
prob4:lab5pc2.c
	gcc -g lab5pc2.c -o prob4 -lpthread
prob5:lab5pc3.c
	gcc -g lab5pc3.c -o prob5 -lpthread
prob6:lab5pc4.c
	gcc -g lab5pc4.c -o prob6 -lpthread
clean:
	rm prob1 prob2 prob3 prob4 prob5 prob6
