all:prob1 prob2 prob3 prob4
prob1:cscd340lab4prob1.c linkedList.c
	gcc -g cscd340lab4prob1.c linkedList.c -o prob1
prob2:cscd340lab4prob2.c
	gcc -g cscd340lab4prob2.c -o prob2
prob3:cscd340lab4prob3.c
	gcc -g cscd340lab4prob3.c -o prob3
prob4:cscd340lab4prob4.c
	gcc -g cscd340lab4prob4.c -o prob4
clean:
	rm prob1 prob2 prob3 prob4
